config/routes.rb
Captaqui::Application.routes.draw do
  resources :betausers

  root :to => 'betausers#new'

  get 'reports' => 'betausers#index'
  get 'thanks' => 'betausers#thanks'

end

app/models/betauser.rb
# -*- encoding : utf-8 -*-
class Betauser < ActiveRecord::Base
  attr_accessible :email, :howmuch, :name


  validates :name, :presence => true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, :uniqueness => { :message => 'Email já registrado.' }
  validates :howmuch, :presence => true
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/betausers_controller.rb
# -*- encoding : utf-8 -*-
class BetausersController < ApplicationController
  # GET /betausers
  # GET /betausers.json
  def index
    @betausers = Betauser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @betausers }
    end
  end

  # GET /betausers/1
  # GET /betausers/1.json
  def show
    @betauser = Betauser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @betauser }
    end
  end

  # GET /betausers/new
  # GET /betausers/new.json
  def new
    @betauser = Betauser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @betauser }
    end
  end

  # GET /betausers/1/edit
  def edit
    @betauser = Betauser.find(params[:id])
  end

  # POST /betausers
  # POST /betausers.json
  def create
    @betauser = Betauser.new(params[:betauser])

    respond_to do |format|
      if @betauser.save
        format.html { render action: 'thanks' }
        format.json { render json: @betauser }
      else
        format.html { render action: 'new' }
        format.json { render json: @betauser.errors, status: :unprocessable_entity }
      end
    end
  end

  def thanks

  end

  # PUT /betausers/1
  # PUT /betausers/1.json
  def update
    @betauser = Betauser.find(params[:id])

    respond_to do |format|
      if @betauser.update_attributes(params[:betauser])
        format.html { redirect_to @betauser, notice: 'Betauser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @betauser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /betausers/1
  # DELETE /betausers/1.json
  def destroy
    @betauser = Betauser.find(params[:id])
    @betauser.destroy

    respond_to do |format|
      format.html { redirect_to betausers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/betausers_helper.rb
# -*- encoding : utf-8 -*-
module BetausersHelper
end

app/views/betausers/_form.html.erb
<%= form_for(@betauser) do |f| %>
  <% if @betauser.errors.any? %>
    <div id="error_explanation">
      <h2>Um ou mais erros impediram cadastro de ser realizado:</h2>

      <ul>
      <% @betauser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <p>

    <%= f.text_field :name, :placeholder => 'Nome' %>

    <%= f.text_field :email, :placeholder => 'e-mail' %>

    <%= f.text_field :howmuch, :placeholder => 'Quanto precisa (R$)?' %>

    <%= f.submit 'Cadastrar para o Beta' %>
<% end %>

app/views/betausers/edit.html.erb
<h1>Editing betauser</h1>

<%= render 'form' %>

<%= link_to 'Show', @betauser %> |
<%= link_to 'Back', betausers_path %>

app/views/betausers/index.html.erb
<h1>Listing betausers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>howmuch</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @betausers.each do |betauser| %>
      <tr>
        <td><%= betauser.name %></td>
        <td><%= betauser.email %></td>
        <td><%= betauser.howmuch %></td>
        <td><%= link_to 'Show', betauser %></td>
        <td><%= link_to 'Edit', edit_betauser_path(betauser) %></td>
        <td><%= link_to 'Destroy', betauser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Betauser', new_betauser_path %>

app/views/betausers/new.html.erb
<div id="fb-root" xmlns="http://www.w3.org/1999/html"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=546890322023473";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<header class="container">
  <div class="col">
    <%= image_tag("/assets/logo.png", :class => 'logo', :alt => 'logo') %>
  </div>
  <div class="col">
    <div class="fb-like" data-href="https://facebook.com/captaqui" data-width="The pixel width of the plugin" data-height="The pixel height of the plugin" data-colorscheme="light" data-layout="button_count" data-action="like" data-show-faces="true" data-send="false"></div>
    <ul class="menu">
      <li><a href="#contato">Contato</a></li>
      <li><a href="http://www.facebook.com/captaqui">Facebook</a></li>

    </ul>

  </div>
  <div class="clear"></div>
</header>
<section class="supercol">
  <div class="container">
    <aside class="bloco">
      <h1>Cultura ganhando vida!</h1>
      <p>Nós conectamos produtores culturais a captadores profissionais para seu projeto encantar cada vez mais a vida das pessoas.</p>
    </aside>
  </div>
</section>
<div class="clear"></div>
<section class="container">
  <div class="col depoimentos">
    <article>
      <%= image_tag("/assets/abre.png", :class => 'abre', :alt => 'abre aspas') %><p>Com uma ferramenta como essa, podemos nos preocupar mais em desenvolver o projeto porque temos certeza que ele terá sua visibilidade. Bem pensado.</p><small>Glaura Lucas</small><img class="fecha" src="/assets/fecha.png" alt="fecha aspas">
    </article>
    <article>
      <%= image_tag("/assets/abre.png", :class => 'abre', :alt => 'abre aspas') %><p>Ja tivemos muitos problemas com captação de projetos. Muita política, muita burocracia, pouco resultado. Com uma ferramenta desse tipo, temos mais chances de captação.</p><small>Bruna Bizzotto</small><img class="fecha" src="/assets/fecha.png" alt="fecha aspas">
    </article>
  </div>
  <div class="col">
    <div class="formulario">
      <h2>Quanto pretende arrecadar?</h2>
        <br />
        <%= render 'form' %>
    </div>
  </div>
  <div class="clear"></div>
</section>

<footer>
  <div class="container" id="contato">
    <hr>
    <h2>euquero@captaqui.com</h2>
    <h3>31 - 7563 0927</h3>
  </div>
  <div class="verde">
    <%= image_tag("/assets/san-pedro.png", :alt => 'made in san pedro Valley') %>
  </div>
</footer>

app/views/betausers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @betauser.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @betauser.email %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @betauser.howmuch %>
</p>

<%= link_to 'Edit', edit_betauser_path(@betauser) %> |
<%= link_to 'Back', betausers_path %>

app/views/betausers/thanks.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=546890322023473";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<header class="container">
  <div class="col">
    <img class="logo" src="/assets/logo.png" alt="logo">
  </div>
  <div class="col">
    <div class="fb-like" data-href="https://facebook.com/captaqui" data-width="The pixel width of the plugin" data-height="The pixel height of the plugin" data-colorscheme="light" data-layout="button_count" data-action="like" data-show-faces="true" data-send="false"></div>
    <ul class="menu">
      <li><a href="http://www.facebook.com/captaqui">Facebook</a></li>
    </ul>
  </div>
  <div class="clear"></div>
</header>
<section class="supercol">
  <div class="container">
    <div class="col">
      <aside class="bloco">
        <% if @betauser %>
            <h1>Muito obrigado pelo interesse <%= @betauser.name %>!</h1>
        <% else %>
            <h1>Obrigado pelo seu cadastro!</h1>
        <% end %>
        <p>Logo mais entraremos em contato para ajudar o seu projeto a crescer!</p>
      </aside>
    </div>
    <div class="col">
      <aside class="bloco-2">
        <p>Enquanto isso, acompanhe nosso <b><a href="http://www.facebook.com/captaqui/">Facebook</a></b> e fique por dentro.</p>
      </aside>
      <aside class="bloco-3">
        <p>Alguma dúvida? Envie um email para: <a href="mailto:euquero@captaqui.com">euquero@captaqui.com</a> </p>
      </aside>
    </div>
  </div>
  <div class="clear"></div>
</section>
<div class="clear"></div>
<footer>
  <div class="branco">
    <%= image_tag("/assets/san-pedro-dark.png", :alt => 'made in san pedro Valley') %>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= display_meta_tags :site =>'Captaqui',
                        :title => 'Conectando seu projeto aos recursos que ele precisa',
                        :description => 'Nós conectamos produtores ou projetos culturais a captadores profissionais para seu projeto abrilhantar cada vez mais a vida das pessoas.',
                        :keywords => 'lei de incentivo, cultura, rouanet, captação, recurso, projeto',
                        :separator => '|'
  %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= javascript_include_tag "application" %>
</body>
</html>